services:
  app:
    image: ghcr.io/remla23-team10/app
    ports:
      - 8080:8080
    environment:
      - MODEL-SERVICE-URL=http://model-service:8080
  
  model-service:
    image: ghcr.io/remla23-team10/model-service
    environment:
      - CLASSIFIER_URL=https://github.com/remla23-team10/model-training/releases/download/latest/BoW_Vectorizer.joblib
      - VECTORIZER_URL=https://github.com/remla23-team10/model-training/releases/download/latest/Classifier_Sentiment_Model.joblib
    ports:
      - 8081:8080