services:
  app:
    image: ghcr.io/remla23-team10/app
    ports:
      - 8080:8080
    environment:
      - MODEL-SERVICE-URL=http://model-service:8080
  
  model-service:
    image: ghcr.io/remla23-team10/model-service
    environment:
      - CLASSIFIER_URL=https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/models/Classifier_Sentiment_Model.joblib
      - VECTORIZER_URL=https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/data/processed/BoW_Vectorizer.joblib
    ports:
      - 8081:8080