apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/remla23-team10/app
          ports:
            - containerPort: 8080
          env:
            - name: MODEL-SERVICE-URL
              value: http://modelservice-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelservice
  template:
    metadata:
      labels:
        app: modelservice
    spec:
      containers:
        - name: modelservice
          image: ghcr.io/remla23-team10/model-service
          ports:
            - containerPort: 8080
---            
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  # type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: modelservice-service
spec:
  selector:
    app: modelservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
  # type: ClusterIP    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  defaultBackend:
    service:
      name: app-service
      port:
        number: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - interval: 30s
    path: /actuator/prometheus