{{if .Values.prometheus.enabled}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: custom-config
spec:
  global:
    smtp_smarthost: 'smtp.gmail.com:587'
  route:
    repeatInterval: 12h
    receiver: 'smtp'
    matchers:
      - name: severity
        value: {{ .Values.prometheus.alertConfig.severity }}


  receivers:
    - name: 'smtp'
      emailConfigs:
      {{- range .Values.prometheus.alertConfig.emails }}
        - to: {{.to}}
          from: {{.from}}
          smarthost: {{.smtphost}}
          authUsername: {{.username}}
          authIdentity: {{.username}}
          authPassword:
            name: smtp-secrets
            key: {{.name}}
          sendResolved: true
      {{- end}}
{{end}}