apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployments.webapp }}
metadata:
  name: {{.name}}-v1
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.selectorLabel}}
      version: v1
      sidecar.istio.io/inject: "true"
  template:
    metadata:
      labels:
        app: app
        version: v1
        sidecar.istio.io/inject: "true"
    spec:
      containers: 
        - name: {{.podname}}
          image: "{{ .repository }}:{{ .tagCE }}"
          ports:
            - containerPort: {{.port}}
          env:
            - name: MODEL-SERVICE-URL
              value: "http://{{ $.Values.services.modelService.name }}:{{ $.Values.services.modelService.port }}"
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
  {{- with .Values.deployments.webapp }}
metadata:
  name: {{.name}}-v0
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.selectorLabel}}
      version: v0
      sidecar.istio.io/inject: "true"
  template:
    metadata:
      labels:
        app: app
        version: v0
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{.podname}}
          image: "{{ .repository }}:{{ .tag }}"
          ports:
            - containerPort: {{.port}}
          env:
            - name: MODEL-SERVICE-URL
              value: "http://{{ $.Values.services.modelService.name }}:{{ $.Values.services.modelService.port }}"
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployments.modelService }}
metadata:
  name: {{.name}}-v1
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.selectorLabel}}
      version: v1
  template:
    metadata:
      labels:
        app: modelservice
        version: v1
        sidecar.istio.io/inject: "true"
    spec:
      containers:  
        - name: {{.podname}}
          image: "{{ .repository }}:{{ .tagCE }}"
          ports:
            - containerPort: {{.port}}
          env:
            - name: CLASSIFIER_URL
              value: "{{ .classifierUrl }}"
            - name: VECTORIZER_URL
              value: "{{ .vectorizerUrl }}"
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployments.modelService }}
metadata:
  name: {{.name}}-v0
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.selectorLabel}}
      version: v0
  template:
    metadata:
      labels:
        app: modelservice
        version: v0
        sidecar.istio.io/inject: "true"
    spec:
      containers:  
        - name: {{.podname}}
          image: "{{ .repository }}:{{ .tag }}"
          ports:
            - containerPort: {{.port}}
          env:
            - name: CLASSIFIER_URL
              value: "{{ .classifierUrl }}"
            - name: VECTORIZER_URL
              value: "{{ .vectorizerUrl }}"
{{- end }}