{{if .Values.prometheus.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
data:
  {{- range .Values.prometheus.alertConfig.emails }}
  {{ .name }}: {{ .password | b64enc }}
  {{- end }}
{{end}}