apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtual-service
spec:
  gateways:
    - gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host:  {{$.Values.services.webapp.name}}
            subset: v1
          weight: 90
        - destination:
            host: {{$.Values.services.webapp.name}}
            subset: v0
          weight: 10