apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtual-service
spec:
  gateways:
    - gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /prometheus
      route:
        - destination:
            host: {{.Release.Name}}-kube-prometheus-stac-prometheus
            port:
              number: 9090
    - match:
        - uri:
            prefix: /grafana
      route:
        - destination:
            host: {{.Release.Name}}-grafana
            port:
              number: 80
    - match:
        - headers:
            x-user-version:
              exact: "v0"
      route:
        - destination:
            host: {{$.Values.services.webapp.name}}
            subset: v0
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{$.Values.services.webapp.name}}
            subset: v1