{
 "title": "Sentiment app dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Accuracy of sentiment analysis model per version",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg by(version) (accuracy)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Review size sum per version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (review_size_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests received by the app per path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(route) (num_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of calls to routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(route) (num_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status returned for received requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (num_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback given on sentiment prediction",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(correct) (review_size_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}