# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployments:
  webapp:
    name: app-deployment
    podname: app
    selectorLabel: app
    repository: ghcr.io/remla23-team10/app
    tag: 1.2.1
    tagCE: 1.3.0
    port: 8080

  modelService:
    name: modelservice-deployment
    podname: modelservice
    selectorLabel: modelservice
    repository: ghcr.io/remla23-team10/model-service
    tag: 1.1.0
    tagCE: 1.2.1
    classifierUrl: https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/models/Classifier_Sentiment_Model.joblib
    vectorizerUrl: https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/data/processed/BoW_Vectorizer.joblib
    port: 8080

services:
  webapp:
    name: app-service
    port: 80
    targetPort: 8080
  
  modelService:
    name: modelservice-service
    port: 80
    targetPort: 8080

serviceMonitor:
  name: app-service-monitor
  interval: 30s


# Deploy the prometheus stack. Can be disabled if you already have a prometheus stack deployed
deploy-prom-stack: true

# alertmanager config
alertConfig:
  severity: warning # minimum level of severity for notification

# List of email configurations. Example using gmail
  emails:
    - name: user                        # name of the config
      to: user@gmail.com                # email to send notifications to
      from: reveiver@example.com        # email to send notifications from
      smtp: smtp.gmail.com:587          # smtp server and port
      username: user@gmail.com          # identity for smtp server
      password: "CHANGE-ME"             # password for smtp server
      # See https://support.google.com/accounts/answer/185833?hl=en for more info on Gmail app passwords

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      externalUrl: http://localhost/prometheus
      routePrefix: /prometheus

  alertmanager:
    config:
      global:
        resolve_timeout: 1m
        # Default smpt server. Ideally same as one of the configs above, but it does not matter
        # since it will use the values from the config.
        # However, the alertmanager refuses to start if there is at least one email reveiver
        # and not a global default smtp server. https://github.com/prometheus/alertmanager/issues/275
        smtp_smarthost: smtp.gmail.com:587

  # Grafana configuration
  grafana:
    env:
      GF_SERVER_ROOT_URL: https://localhost:3000/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
    # username is 'admin'
    adminPassword: prom-operator
    defaultDashboardsEnabled: false
