# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployments:
  webapp:
    name: app-deployment
    podname: app
    selectorLabel: app
    repository: ghcr.io/remla23-team10/app
    tags:
      - tag: 1.2.1
        version: v0
      - tag: 1.3.0 # tagCE
        version: v1
    port: 8080

  modelService:
    name: modelservice-deployment
    podname: modelservice
    selectorLabel: modelservice
    repository: ghcr.io/remla23-team10/model-service
    tags:
      - tag: 1.1.0
        version: v0
      - tag: 1.2.1 # tagCE
        version: v1
    classifierUrl: https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/models/Classifier_Sentiment_Model.joblib
    vectorizerUrl: https://github.com/remla23-team10/model-training/raw/f3325ef89c0245cc94fdcadcecee45e9b8a560b7/data/processed/BoW_Vectorizer.joblib
    port: 8080

services:
  webapp:
    name: app-service
    port: 80
    targetPort: 8080
  
  modelService:
    name: modelservice-service
    port: 80
    targetPort: 8080

serviceMonitor:
  name: app-service-monitor
  interval: 30s


# If prometheus is used, describe if the predefined AlertManager, PrometheusRule and ServiceMonitor should be deployed as well
prometheus:
  enabled: true
  alertConfig:
    severity: warning # minimum level of severity for notification
      # List of email configurations. Example using gmail
    emails:
        - name: user                        # name of the config
          to: user@gmail.com                # email to send notifications to
          from: reveiver@example.com        # email to send notifications from
          smtp: smtp.gmail.com:587          # smtp server and port
          username: user@gmail.com          # identity for smtp server
          password: "CHANGE-ME"             # password for smtp server
      # See https://support.google.com/accounts/answer/185833?hl=en for more info on Gmail app passwords

# If grafana is used, describe if the predefined dashboards in "dashboards" should be deployed as well
grafana:
  enabled: true

# If istio is used, describe if the predefined DestinationRule, EnvoyFilter, Gateway and VirtualService should be deployed as well
istio:
  enabled: true